apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ymwnh54xh-java-quarkus 
  janus-idp.io/tekton: ymwnh54xh-java-quarkus
  backstage.io/kubernetes-id: ymwnh54xh-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ymwnh54xh-java-quarkus
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml